
sudo: false

language: node_js
node_js:
  - "0.12"

addons:
  code_climate:
    repo_token: 9837c47ff03909a7992587ec82078fd438dc2969feec995d70e77138f3388415

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli codeclimate-test-reporter

script:
  - grunt travis --verbose

after_script:
  - codeclimate-test-reporter < coverage/*/lcov.info
